### ISSUE TITLE
Two Factor - Email - User model doesnt get init properly

### ISSUE THREAD

**Issue by deadmantfa** [2amigos/yii2-usuario#513] opened 2023-04-07 15:08 UTC
### What steps will reproduce the problem?
Enable Two-Factor Email. Logout. Try Loging in - Error Message

### What is the expected result?
Email to be sent with the code

### What do you get instead?
Error message - Unable to send email

**Comment by edegaudenzi** [comment] 2023-09-22 15:51
**Context**
Had same problem with **2amigos/yii2-usuario** version **1.6.1** and a custom User model that extends the yii2-usuario one. 

**Problem**
Found out the problem is syntactical and it's actually in:

`vendor/2amigos/yii2-usuario/src/User/Validator/TwoFactorEmailValidator.php line 114`

at this line the trait method `make()` is used, passing the class we want to make as the first argument, and the `$this->user` as a second argument; and the problem is here!
The trait method `make()` uses the `yii\di\Container::get()` method, which accepts **an array** as a second parameter. It does not throw an exception probably because the User object is silently cast in array, so the argument is still formally valid.

**Solution**
Coming back to `TwoFactorEmailValidator.php line 114`, if instead of 
`return $this->make(TwoFactorEmailCodeGeneratorService::class, $this->user)->run();`
you use
`return $this->make(TwoFactorEmailCodeGeneratorService::class, [$this->user])->run();`

then everything starts to work. 

Hope to have been useful, I will submit a pull request if someone else doesn't beat me on time.

Live long and prosper \\//_

**Comment by deadmantfa** [comment] 2023-09-23 16:39
There is a PR already there #519 with the fixes its not merged yet

**Comment by edegaudenzi** [comment] 2023-09-25 14:53
Thank you deadmantfa, didn't see it before doing mine.
For readers: 
- [edegaudenzi](https://github.com/edegaudenzi) [PR](https://github.com/2amigos/yii2-usuario/pull/523) is a one-liner and only solves [#513](https://github.com/2amigos/yii2-usuario/issues/513).
- [deadmantfa](https://github.com/deadmantfa) [PR](https://github.com/2amigos/yii2-usuario/pull/519) solves both [#513](https://github.com/2amigos/yii2-usuario/issues/513) (same one-liner) and [#515](https://github.com/2amigos/yii2-usuario/issues/515) in one go.

**Comment by maxxer** [comment] 2023-12-15 11:15
PR merged, should fix this issue

**Closed by maxxer** 2023-12-15 11:15 UTC
