### ISSUE TITLE
ReCaptha fails with "unknown property"

### ISSUE THREAD

**Issue by BillHeaton** [2amigos/yii2-usuario#347] opened 2019-09-08 20:38 UTC
### What steps will reproduce the problem?
Follow the steps in yii2-usuario/docs/helpful-guides/how-to-use-recaptcha-widget.md to implement ReCaptcha for RegistrationForm

Attempt to register a new user.

### What is the expected result?
User model updated with new user info

### What do you get instead?
Exception
> Unknown Property – yii\base\UnknownPropertyException
> Setting unknown property: Da\User\Model\User::captcha

### Solution 

Adding any field to the registration form fails because the container doesn't know what to do with the extra field(s). The solution is to only pass the fields that the user model expects to show up. 

**Change in src/User/Controller/RegistrationController.php/actionRegister():**

```
 $user = $this->make(User::class, [], $form->attributes);
```
**To:**
```
 $user = $this->make(User::class, [],
      [ 'email'    => $form->attributes['email'],
        'username' => $form->attributes['username'],
        'password' => $form->attributes['password']
      ]);
```

**Comment by Thoulah** [comment] 2019-09-08 21:02
Seems like to failed to follow step 1: [Override the Form](https://github.com/2amigos/yii2-usuario/blob/master/docs/helpful-guides/how-to-add-captcha-widget.md#override-the-form)

**Comment by BillHeaton** [comment] 2019-09-08 21:05
It was followed.  Did you read the portion marked: "Solution"?  it explained the problem and the soluction.  Bil

**Comment by demonking** [comment] 2019-09-08 21:13
I think you missed this step ...

https://github.com/2amigos/yii2-usuario/blob/master/docs/helpful-guides/how-to-add-captcha-widget.md#configure-module-and-application

**Comment by BillHeaton** [comment] 2019-09-08 21:16
Yes I configured the module.  Did you miss the explanation that under "Solution?"

**Comment by Thoulah** [comment] 2019-09-08 21:18
> It was followed. I explained the problem and the solution in the section "Solution"

Not really, your 'solution' is a failure. Just image what happens to the field with that code.

**Comment by BillHeaton** [comment] 2019-09-08 21:20
Please explain how it is a failure...
> > It was followed. I explained the problem and the solution in the section "Solution"
> 
> Not really, your 'solution' is a failure. Just image what happens to the field with that code.

**Comment by demonking** [comment] 2019-09-08 21:22
The Problem is, that you say, you followed the Step's from the guide.
Why you not provide your steps, which you have done?

This snippet is only one small part of the guide

**Comment by BillHeaton** [comment] 2019-09-08 21:26
The snippet is not apart of the guide.

**Comment by demonking** [comment] 2019-09-08 21:32
You say, that you override this action...

src/User/Controller/RegistrationController.php/actionRegister

Your suggestion is bad, because you will have to update your action for every new attribute...

**Comment by BillHeaton** [comment] 2019-09-08 21:35
Until it's updated in github.  I'm working on setting up a pull request.  

> You say, that you have to override this action...
> 
> src/User/Controller/RegistrationController.php/actionRegister
> 
> Your suggestion is bad, because you will have to update your action for every new attribute...
> 
> Seems like no other had problem with this, so please post more Code and your steps.

**Comment by Thoulah** [comment] 2019-09-08 21:37
> Seems like no other had problem with this, so please post more Code and your steps.

Same for the other issues created yesterday. I have implemented captcha into the registration form and never ran in any of these problems.
@BillHeaton You must have done something wrong or missed a step. Please share exactly what you have done, as your 'solutions' are not solutions and most likely will never be part of the code. You better focus on the real issue instead of shady workarounds.

**Comment by BillHeaton** [comment] 2019-09-08 21:59
### Configuring the ReCaptchaComponent
```
		'recaptcha' => [ // *important* this name must be like this
        	'class' 	=> 'Da\User\Component\ReCaptchaComponent',
			'key' 		=> '_redacted_',
			'secret' 	=> '_redacted_'
		],

```

### Override the Form

```
namespace app\models\Forms;
use Da\User\Form\RecoveryForm as BaseForm;

class RecoveryForm extends BaseForm {
    public $captcha;

    public function rules() {
        $rules = parent::rules();

        $rules[] = [['captcha'], 'required'];
        $rules[] = [['captcha'], 'safe'];
        $rules[] = [['captcha'], 'Da\User\Validator\ReCaptchaValidator'];

        return $rules;
    }
    
    public function scenarios()
    {
        return [
            self::SCENARIO_REQUEST => ['email', 'captcha'],
            self::SCENARIO_RESET => ['password'],
        ];
    }
}
```

### Overriding the View
```
[use yii\helpers\Html;
use yii\widgets\ActiveForm;
use Da\User\Widget\ReCaptchaWidget;

$this->title = Yii::t('usuario', 'Recover your password');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="panel-body">
                <?php $form = ActiveForm::begin(
                    [
                        'id' => $model->formName(),
                        'enableAjaxValidation' => false,
                        'enableClientValidation' => false,
                    ]
                ); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'captcha')->label('')
	                ->widget(ReCaptchaWidget::className(), ['theme' => 'light']) ?>

                <?= Html::submitButton(Yii::t('usuario', 'Continue'), ['class' => 'btn btn-primary btn-block']) ?><br>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>
```
### Configure Module and Application

```
        'user' => [
            'class' => Da\User\Module::class,
            'administrators' => ['daddy'],
        
            'classMap' => [
                'RegistrationForm'	=> 'app\models\Forms\RegistrationForm',
                'ResendForm' 		=> 'app\models\Forms\ResendForm',
                'RecoveryForm' 		=> 'app\models\Forms\RecoveryForm',
            ],
        	
            'mailParams' => [ 'fromEmail' => 'webmaster@daddysreviews.com', ],
        
        ]

```

**Comment by Thoulah** [comment] 2019-09-09 19:21
I just switch from another ReCaptcha widget to the Da one following the [guide](https://yii2-usuario.readthedocs.io/en/latest/helpful-guides/how-to-use-recaptcha-widget/) and it just works. Only difference was to set `enableAjaxValidation` to false (#346 confirmed!)

**Comment by BillHeaton** [comment] 2019-09-09 20:14
Thank you!  Which form did you add the ReCaptcha to?

**Comment by Thoulah** [comment] 2019-09-10 10:52
Registration

**Comment by BillHeaton** [comment] 2019-09-14 03:02
@Thoulah,  I just reran the test using GitHub versions of yii2, yii2-app-basic, and yii2-usuario using the "How to Use ReCaptcha Widget" modified to add ReCaptcha to the registration form.

Attempting to register a new user resullts in a "Setting unknown property: Da\User\Model\User::captchayii\base\UnknownPropertyException:"  Applying the fix to src/User/Controller/RegistrationController.php/actionRegister mentioned above solved the problem.

Since we're getting different results we should compare notes.  I'm going to go ahead and submit the fix.

**Comment by demonking** [comment] 2019-09-16 12:17
ok long time ago don't have time to take it further..

Let's see in the guide 
https://github.com/2amigos/yii2-usuario/blob/master/docs/helpful-guides/how-to-use-recaptcha-widget.md


I'm a bit confused by your code now .

You say 

> Attempting to register a new user resullts in a "Setting unknown property: Da\User\Model\User::captchayii\base\UnknownPropertyException:
Setting unknown property: Da\User\Model\User::captchayii\base\UnknownPropertyException: "

But your Code from above is for the RecoveryForm?! 
When i look in the list of Controller i find a RegistrationController.

Maybe you have missed this step?

Also i'm missing the components->view->theme->pathMap ?

**Comment by BillHeaton** [comment] 2019-09-16 12:57
I've successfully added ReCaptcha to three outward facing forms: _RecoveryForm_, _RegistrationForm_, and _RecoveryForm_ using the guide for each of three forms.  

#346 applies to all three forms as AJAX fails for ReCaptcha.  
#345 only applies to RecoveryForm as it uses a scenario.  
#347 only  applies to RegistrationForm because it's the only one that directly uses the _User_ model.

No I did not miss the _pathmap_ step.  I've updated the post above to reflect that.

**Comment by tonydspaniard** [comment] 2019-09-17 15:56
@BillHeaton see #351

**Comment by maxxer** [comment] 2019-11-25 21:52
I'm closing this as the PR has been merged, please reopen if you still have issues. Thanks

**Closed by maxxer** 2019-11-25 21:52 UTC
Labels: under investigation
